name: Check packages

on:
  push:
    paths:
      - 'packages/**'

jobs:
  changed-files:
    name: 'Get changed files'
    runs-on: ubuntu-latest

    outputs:
      packages: ${{ steps.changed_files.outputs.all_changed_files }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Get changed directory names
        id: changed_files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            packages/**
          dir_names: "true"
          dir_names_exclude_current_dir: "true"

  run-npm-bootstrap:
    name: 'Run npm bootstrap in modified package'
    runs-on: ubuntu-latest

    needs: changed-files

    if: needs.changed-files.outputs.packages != ''

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure git
        run: git config --global url."https://".insteadOf git:// && git config --global url."https://github.com/".insteadOf 'git@github.com:'

      - name: Run npm bootstrap
        run: npm run bootstrap
